# Site settings
title: Minjoon Seo
name: Minjoon Seo
korean_name: 서민준
email: minjoon@lklab.io
gmail: seominjoon@gmail.com
occupation: Assistant Professor
employer: KAIST
office: Seoul Campus Building 9 Suite 202
department: Kim Jaechul Graduate School of AI
description: > # this means to ignore newlines until "baseurl:"
  Minjoon Seo, Assistant Professor at KAIST
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seominjoon.github.io" # the base hostname & protocol for your site
twitter_username: seo_minjoon
github_username:  seominjoon

# Build settings
markdown: kramdown
