# Site settings
title: Doyoung Kim
name: Doyoung Kim
korean_name: 김도영
email: doyoung@lklab.io
gmail: doyoung9803@gmail.com
occupation: Masters Degree at AI
employer: KAIST
office: Seoul Campus Building 9209
department: Kim Jaechul Graduate School of AI
description: > # this means to ignore newlines until "baseurl:"
  Minjoon Seo, Assistant Professor at KAIST
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://doyoungkim.github.io" # the base hostname & protocol for your site
twitter_username: doyoungkim_nlp
github_username:  doyoungkim-nlp

# Build settings
markdown: kramdown
