# Site settings
title: Minjoon Seo
name: Minjoon Seo
korean_name: 서민준
email: seominjoon@gmail.com
occupation: Assistant Professor
employer: KAIST School of AI
office: CSE 386
department: Graduate School of AI
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Minjoon Seo, UW CSE PhD student
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seominjoon.github.io" # the base hostname & protocol for your site
twitter_username: seo_minjoon
github_username:  seominjoon

# Build settings
markdown: kramdown
